### PR TITLE
Fix vulnerability

### PR DESCRIPTION
**Pull request by tianhuil**
Fixing this issue: https://github.com/prisma/prisma/issues/4738

### CODE REVIEW

**Comment by tianhuil** [comment]
@mavilein, @do4gr, @nikolasburk, @timsuchanek: any thoughts on merging this?

**Comment by mavilein** [comment]
@tianhuil : Thanks for submitting this fix and also for pinging us! I will ask @timsuchanek to follow up who is our resident javascript expert.

**Comment by timsuchanek** [comment]
Hi @tianhuil, thanks a lot for the PR! I just checked, the `marked` dependency is not in use anymore, the method it's defined in isn't used in our code.
So 2 asks:
Optimally you even remove that code in a PR.
In both cases: Please do the PR against the `alpha` branch.

**Comment by tianhuil** [comment]
@timsuchanek: thanks for the reply (sorry for the lateness, I don't check GitHub that often).

I don't think we can just remove the dependency (see below from the `alpha` branch) but I'm happy to redo this PR against the `alpha` branch.

```
$ git grep marked -- **.ts
cli/packages/prisma-cli-engine/src/Output/index.ts:import * as marked from 'marked'
cli/packages/prisma-cli-engine/src/Output/index.ts:import * as TerminalRenderer from 'marked-terminal'
cli/packages/prisma-cli-engine/src/Output/index.ts:marked.setOptions({
cli/packages/prisma-cli-engine/src/Output/index.ts:    this.log(marked(markdown))
```

**Comment by gustawdaniel** [comment]
Hey. 

+ What need to be done to accept this pull request? 
+ Is any person responsible for this? 
+ How can I help?

**Pull request closed without merging**
