### PR TITLE
Fixing vulnerability

### PR DESCRIPTION
**Pull request by tianhuil**
https://github.com/prisma/prisma/issues/4738

See: https://github.com/prisma/prisma/pull/4739

### CODE REVIEW

**Comment by gustawdaniel** [comment]
Npm audit shows

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ marked                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.6.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ prisma                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ prisma > prisma-cli-engine > marked                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/812                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ marked                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.7.0                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ prisma                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ prisma > prisma-cli-engine > marked                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1076                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

So why `0.6.2` version instead of `0.7.0` is chosen?

**Comment by gustawdaniel** [comment]
Why no one accepted this pull request?

@steebchen I see that you have last merged pull request. Do you know what criteria need to be satisfied for pull request acceptance or rejection? Who can make decision in this topic?

**Comment by dannyfreeman** [comment]
Is this ever going to get merged in?

**Comment by gustawdaniel** [comment]
@dannyfreeman Probably something terrible happened in prisma development team

Screenshot from 2019-12-05 20-43-22

Frequency of commits dropped down dramatically.

**Comment by steebchen** [comment]
Hey guys, this is likely not ever going to be merged, as this repository is unmaintained in favor of the Prisma Framework ("Prisma 2") where all our development goes into. For more information, see the pinned issue https://github.com/prisma/prisma/issues/4898.

Regarding the content of this PR, we don't believe this is critical to fix as this just affects the CLI, which you will not use on a production server. If you want to see what we're up to these days, please check out https://github.com/prisma/prisma2.

**Comment by dannyfreeman** [comment]
Thanks for linked that pinned issue. I hadn't seen it before. It would still be nice to see this change included with the next round of security and maintenance fixes that the linked issues says will still be happening. So long as the new version of this dependency hasn't introduced any breaking changes for the cli.

**Pull request closed without merging**
