### PR TITLE
Extended architecture compatibility (ARM and more)

### PR DESCRIPTION
**Pull request by kazazes**
Switching the prisma base image to [`openjdk:8-slim`](https://github.com/docker-library/openjdk/blob/c3023e4da10d10e9c9775eabe2d7baac146e7ae1/8/jdk/slim/Dockerfile) maintains compatability with `anapsix/alpine-java` (glibc), instantly enables multi-arch docker images (yay ARM!), and increases future stability and security by depending on an official image.

In terms of testing, PG's image also comes with ARM support out of the box, so I've replaced `timms/postgres-logging` with the official PG image and added the old image's logging script.

PG's tests maintain current coverage on amd64 and armhf. There are no official MySQL or Mongo docker images for ARM, so I'll leave that be for now.

In terms of CI for ARM images, running [cross builds](https://www.balena.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/) like @balena-io does has worked wonders for me, but I'll leave that to the prisma team.

In the interim, [`pckzs/prisma`](https://hub.docker.com/r/pckzs/prisma) is multi-arch compatible image on the prisma/prisma@617c80d release. I will make it an automated build if this PR doesn't get traction.

- [ ] Is there a reason prisma depended on the Oracle JDK?
- [ ] The ARM build needs further (live) testing.

Addresses #2909 and #2207.

### CODE REVIEW

**Comment by mavilein** [comment]
@kazazes : Thanks a lot for providing this PR! 🙏  We just discussed this internally and this looks really interesting to us. However we can't merge it right now. The reason is that we have a big PR (https://github.com/prisma/prisma/pull/3695) pending. This PR will affect our build heavily and we would like to get this one merged before we move on with the ARM support.

**Comment by kazazes** [comment]
@mavilein, no rush! I’ll add ARM cross compilation in the mean time. Is using the openjdk base image acceptable internally?

**Comment by mavilein** [comment]
@kazazes : Yeah nothing speaks against that. Recently we just considered to use the GraalVM image as it is said to be around 10% faster.

**Comment by kazazes** [comment]
@mavilein, can this be revisited now?

**Comment by lysenkobv** [comment]
I also faced with the problem on Raspberry PI. Hope this PR can be finally merged in the nearest future. @kazazes, thank you for this PR!

**Comment by mavilein** [comment]
Hey @kazazes 👋 ,
sorry we did not have the chance yet to look into this. A colleague will try to look into it over the coming days. However right now i can't promise we will be able to do it. We are currently reimplementing Prisma in Rust and are therefore very busy. But ARM support is on our list of things we will definitely support with our Rust version!

**Comment by mitswan** [comment]
@kazazes this is exactly what I am looking for! has there been any progress on having it merged?

**Comment by sbonami** [comment]
Bumping 😬

**Comment by dijbi** [comment]
Bumping :)

**Pull request closed without merging**
